SHELL := /bin/sh
PYTHON ?= python3
export PYTHONPATH := $(CURDIR)/src

ifneq (,$(wildcard .env))
include .env
export OPENAI_API_KEY OPENROUTER_API_KEY RELIABMEM_PROVIDER RELIABMEM_MODEL
export RELIABMEM_EMBEDDING_MODEL RELIABMEM_CONFIRMATION_MODEL RELIABMEM_BASE_URL
export RELIABMEM_REASONING_EFFORT OPENROUTER_SITE_URL OPENROUTER_APP_TITLE
export RELIABMEM_INPUT_PRICE_PER_MILLION RELIABMEM_OUTPUT_PRICE_PER_MILLION
export RELIABMEM_CACHED_INPUT_PRICE_PER_MILLION RELIABMEM_CACHE_WRITE_PRICE_PER_MILLION
export RELIABMEM_REQUEST_PRICE_USD RELIABMEM_EMBEDDING_INPUT_PRICE_PER_MILLION
export RELIABMEM_EMBEDDING_OUTPUT_PRICE_PER_MILLION
export RELIABMEM_EMBEDDING_CACHED_INPUT_PRICE_PER_MILLION
export RELIABMEM_EMBEDDING_CACHE_WRITE_PRICE_PER_MILLION
export RELIABMEM_EMBEDDING_REQUEST_PRICE_USD
endif

.PHONY: paper test generate smoke clean

paper:
	$(PYTHON) -m reliabmem.pipeline paper

test:
	$(PYTHON) -m unittest discover -s tests -v

generate:
	$(PYTHON) -m reliabmem.pipeline generate

smoke:
	$(PYTHON) -m reliabmem.pipeline smoke

clean:
	$(PYTHON) -m reliabmem.pipeline clean
